In [1]:
import nltk
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# nltk.download("punkt")
# nltk.download("wordnet")

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
sentences = nltk.sent_tokenize(paragraph)
wordnet = WordNetLemmatizer()
stemmer = PorterStemmer()
corpus = []

In [4]:
for i in range(len(sentences)):
    review = re.sub('[^a-xA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = " ".join(review)
    corpus.append(review)
len(corpus)

31

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
corpus_1 = []
for i in range(len(sentences)):
    review = re.sub('[^a-xA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review = " ".join(review)
    corpus_1.append(review)
len(corpus_1)

31

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv_1 = CountVectorizer()
y = cv_1.fit_transform(corpus_1).toarray()
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
import pandas as pd
import numpy as np

In [9]:
x_dataframe = pd.DataFrame(x)
y_dataframe = pd.DataFrame(y)

In [10]:
x_dataframe.head()

0    1    2    3    4    5    6    7    8    9    ...  105  106  107  108  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    1    0    0    0    0    0    0    1    0  ...    1    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   109  110  111  112  113  114  
0    0    0    0    0    0    0  
1    0    0    0    0    1    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    1  
4    0    0    0    0    0    0  

[5 rows x 115 columns]

In [11]:
y_dataframe.head()

0    1    2    3    4    5    6    7    8    9    ...  104  105  106  107  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    1   
1    0    0    0    0    0    0    0    0    0    0  ...    0    1    0    0   
2    0    1    0    0    0    0    0    0    1    0  ...    0    1    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   108  109  110  111  112  113  
0    0    0    0    0    0    0  
1    0    0    0    0    1    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    1  
4    0    0    0    0    0    0  

[5 rows x 114 columns]